-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE view published_article AS
-- SELECT * FROM public.article
-- WHERE public.article.status = 'published';
